//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:23:03 PM EEST 
//


package gr.ntua.ivml.mint.uim.messages.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gr.ntua.ivml.mint.uim.messages.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PublishTransformation_QNAME = new QName("", "PublishTransformation");
    private final static QName _CreateImport_QNAME = new QName("", "CreateImport");
    private final static QName _ImportExists_QNAME = new QName("", "ImportExists");
    private final static QName _CreateUser_QNAME = new QName("", "CreateUser");
    private final static QName _GetTransformations_QNAME = new QName("", "GetTransformations");
    private final static QName _OrganizationExists_QNAME = new QName("", "OrganizationExists");
    private final static QName _Publication_QNAME = new QName("", "Publication");
    private final static QName _GetImports_QNAME = new QName("", "GetImports");
    private final static QName _UserExists_QNAME = new QName("", "UserExists");
    private final static QName _CreateOrganization_QNAME = new QName("", "CreateOrganization");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.ntua.ivml.mint.uim.messages.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PublicationCommand }
     * 
     */
    public PublicationCommand createPublicationCommand() {
        return new PublicationCommand();
    }

    /**
     * Create an instance of {@link PublicationResponse }
     * 
     */
    public PublicationResponse createPublicationResponse() {
        return new PublicationResponse();
    }

    /**
     * Create an instance of {@link CreateImportAction }
     * 
     */
    public CreateImportAction createCreateImportAction() {
        return new CreateImportAction();
    }

    /**
     * Create an instance of {@link PublishTransformationAction }
     * 
     */
    public PublishTransformationAction createPublishTransformationAction() {
        return new PublishTransformationAction();
    }

    /**
     * Create an instance of {@link ImportExistsAction }
     * 
     */
    public ImportExistsAction createImportExistsAction() {
        return new ImportExistsAction();
    }

    /**
     * Create an instance of {@link CreateUserAction }
     * 
     */
    public CreateUserAction createCreateUserAction() {
        return new CreateUserAction();
    }

    /**
     * Create an instance of {@link GetTransformationsAction }
     * 
     */
    public GetTransformationsAction createGetTransformationsAction() {
        return new GetTransformationsAction();
    }

    /**
     * Create an instance of {@link PublicationAction }
     * 
     */
    public PublicationAction createPublicationAction() {
        return new PublicationAction();
    }

    /**
     * Create an instance of {@link OrganizationExistsAction }
     * 
     */
    public OrganizationExistsAction createOrganizationExistsAction() {
        return new OrganizationExistsAction();
    }

    /**
     * Create an instance of {@link GetImportsAction }
     * 
     */
    public GetImportsAction createGetImportsAction() {
        return new GetImportsAction();
    }

    /**
     * Create an instance of {@link UserExistsAction }
     * 
     */
    public UserExistsAction createUserExistsAction() {
        return new UserExistsAction();
    }

    /**
     * Create an instance of {@link CreateOrganizationAction }
     * 
     */
    public CreateOrganizationAction createCreateOrganizationAction() {
        return new CreateOrganizationAction();
    }

    /**
     * Create an instance of {@link GetTransformationsCommand }
     * 
     */
    public GetTransformationsCommand createGetTransformationsCommand() {
        return new GetTransformationsCommand();
    }

    /**
     * Create an instance of {@link CreateOrganizationResponse }
     * 
     */
    public CreateOrganizationResponse createCreateOrganizationResponse() {
        return new CreateOrganizationResponse();
    }

    /**
     * Create an instance of {@link CreateOrganizationCommand }
     * 
     */
    public CreateOrganizationCommand createCreateOrganizationCommand() {
        return new CreateOrganizationCommand();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link ImportExistsCommand }
     * 
     */
    public ImportExistsCommand createImportExistsCommand() {
        return new ImportExistsCommand();
    }

    /**
     * Create an instance of {@link OrganizationExistsResponse }
     * 
     */
    public OrganizationExistsResponse createOrganizationExistsResponse() {
        return new OrganizationExistsResponse();
    }

    /**
     * Create an instance of {@link OrganizationExistsCommand }
     * 
     */
    public OrganizationExistsCommand createOrganizationExistsCommand() {
        return new OrganizationExistsCommand();
    }

    /**
     * Create an instance of {@link UserExistsCommand }
     * 
     */
    public UserExistsCommand createUserExistsCommand() {
        return new UserExistsCommand();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link GetImportsResponse }
     * 
     */
    public GetImportsResponse createGetImportsResponse() {
        return new GetImportsResponse();
    }

    /**
     * Create an instance of {@link CreateUserCommand }
     * 
     */
    public CreateUserCommand createCreateUserCommand() {
        return new CreateUserCommand();
    }

    /**
     * Create an instance of {@link CreateImportCommand }
     * 
     */
    public CreateImportCommand createCreateImportCommand() {
        return new CreateImportCommand();
    }

    /**
     * Create an instance of {@link PublishTransformationResponse }
     * 
     */
    public PublishTransformationResponse createPublishTransformationResponse() {
        return new PublishTransformationResponse();
    }

    /**
     * Create an instance of {@link ImportExistsResponse }
     * 
     */
    public ImportExistsResponse createImportExistsResponse() {
        return new ImportExistsResponse();
    }

    /**
     * Create an instance of {@link GetImportsCommand }
     * 
     */
    public GetImportsCommand createGetImportsCommand() {
        return new GetImportsCommand();
    }

    /**
     * Create an instance of {@link UserExistsResponse }
     * 
     */
    public UserExistsResponse createUserExistsResponse() {
        return new UserExistsResponse();
    }

    /**
     * Create an instance of {@link GetTransformationsResponse }
     * 
     */
    public GetTransformationsResponse createGetTransformationsResponse() {
        return new GetTransformationsResponse();
    }

    /**
     * Create an instance of {@link CreateImportResponse }
     * 
     */
    public CreateImportResponse createCreateImportResponse() {
        return new CreateImportResponse();
    }

    /**
     * Create an instance of {@link PublicationCommand.IncludedImports }
     * 
     */
    public PublicationCommand.IncludedImports createPublicationCommandIncludedImports() {
        return new PublicationCommand.IncludedImports();
    }

    /**
     * Create an instance of {@link PublicationResponse.IncludedImport }
     * 
     */
    public PublicationResponse.IncludedImport createPublicationResponseIncludedImport() {
        return new PublicationResponse.IncludedImport();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishTransformationAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PublishTransformation")
    public JAXBElement<PublishTransformationAction> createPublishTransformation(PublishTransformationAction value) {
        return new JAXBElement<PublishTransformationAction>(_PublishTransformation_QNAME, PublishTransformationAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateImportAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateImport")
    public JAXBElement<CreateImportAction> createCreateImport(CreateImportAction value) {
        return new JAXBElement<CreateImportAction>(_CreateImport_QNAME, CreateImportAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportExistsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ImportExists")
    public JAXBElement<ImportExistsAction> createImportExists(ImportExistsAction value) {
        return new JAXBElement<ImportExistsAction>(_ImportExists_QNAME, ImportExistsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateUser")
    public JAXBElement<CreateUserAction> createCreateUser(CreateUserAction value) {
        return new JAXBElement<CreateUserAction>(_CreateUser_QNAME, CreateUserAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTransformationsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GetTransformations")
    public JAXBElement<GetTransformationsAction> createGetTransformations(GetTransformationsAction value) {
        return new JAXBElement<GetTransformationsAction>(_GetTransformations_QNAME, GetTransformationsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationExistsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OrganizationExists")
    public JAXBElement<OrganizationExistsAction> createOrganizationExists(OrganizationExistsAction value) {
        return new JAXBElement<OrganizationExistsAction>(_OrganizationExists_QNAME, OrganizationExistsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicationAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Publication")
    public JAXBElement<PublicationAction> createPublication(PublicationAction value) {
        return new JAXBElement<PublicationAction>(_Publication_QNAME, PublicationAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetImportsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GetImports")
    public JAXBElement<GetImportsAction> createGetImports(GetImportsAction value) {
        return new JAXBElement<GetImportsAction>(_GetImports_QNAME, GetImportsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserExistsAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserExists")
    public JAXBElement<UserExistsAction> createUserExists(UserExistsAction value) {
        return new JAXBElement<UserExistsAction>(_UserExists_QNAME, UserExistsAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrganizationAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CreateOrganization")
    public JAXBElement<CreateOrganizationAction> createCreateOrganization(CreateOrganizationAction value) {
        return new JAXBElement<CreateOrganizationAction>(_CreateOrganization_QNAME, CreateOrganizationAction.class, null, value);
    }

}
