//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.27 at 06:22:47 PM EEST 
//


package gr.ntua.ivml.mint.uim.messages.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="PublishTransformationResponse" type="{}PublishTransformationResponse"/>
 *         &lt;element name="Error" type="{}ErrorResponse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "publishTransformationResponse",
    "error"
})
@XmlRootElement(name = "PublishTransformation")
public class PublishTransformation {

    @XmlElement(name = "PublishTransformationResponse")
    protected PublishTransformationResponse publishTransformationResponse;
    @XmlElement(name = "Error")
    protected ErrorResponse error;

    /**
     * Gets the value of the publishTransformationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link PublishTransformationResponse }
     *     
     */
    public PublishTransformationResponse getPublishTransformationResponse() {
        return publishTransformationResponse;
    }

    /**
     * Sets the value of the publishTransformationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishTransformationResponse }
     *     
     */
    public void setPublishTransformationResponse(PublishTransformationResponse value) {
        this.publishTransformationResponse = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorResponse }
     *     
     */
    public ErrorResponse getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorResponse }
     *     
     */
    public void setError(ErrorResponse value) {
        this.error = value;
    }

}
