/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-04-03 11:15:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.log4j.Logger;
import gr.ntua.ivml.mint.persistent.User;
import gr.ntua.ivml.mint.db.DB;
import gr.ntua.ivml.mint.util.Config;

public final class datastatistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 public final Logger log = Logger.getLogger(this.getClass());
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/_include.jsp", Long.valueOf(1395664770000L));
    _jspx_dependants.put("/WEB-INF/jsp/customize.tld", Long.valueOf(1395664770000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

log.debug( "Output rendered" );

User user=(User) request.getSession().getAttribute("user");
if( user != null ) {
	user = DB.getUserDAO().findById(user.getDbID(), false );
}

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("   ");
      if (_jspx_meth_s_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("   \n");
      out.write("\n");
      out.write("<div class=\"panel-body\">\n");
      out.write(" <div class=\"block-nav\">\n");
      out.write(" \t<div class=\"summary\">\n");
      out.write("\t<div class=\"label\">\n");
      out.write("   </div>  \n");
      out.write("    ");
 if( request.getAttribute( "actionmessage" ) != null ) {  
      out.write("\n");
      out.write("\t\t<div class=\"info\"><div class=\"errorMessage\"></div>\n");
      out.write("\t\t");
      out.print((String) request.getAttribute( "actionmessage" ));
      out.write("</div>\n");
      out.write("      ");
}else{
      out.write("\n");
      out.write("    <div class=\"info\">\n");
      out.write("\t\tView organization and project statistics:\n");
      out.write("\t</div>");
} 
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("    <div\n");
      out.write("\t\t\tstyle=\"display: block; padding: 5px 0 0 5px; background: #F2F2F2; border-bottom: 1px solid #CCCCCC;\">\n");
      out.write("\t\t\t<span style=\"width: 150px; display: inline-block\"></span>\n");
      out.write("\t\t\t");
      if (_jspx_meth_s_005fselect_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t \n");
      out.write("\t \n");
      out.write("\t<div title=\"Organization overall\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'OrgItemStats.action?organizationId='+$('#filterorg').val(), kTitle:'Organization statistics' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Organization overall</div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t \n");
      out.write("\t \n");
      out.write("\t <!-- <div title=\"Organization overall\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'OrgItemStats.action?organizationId='+$('#filterorg').val(), kTitle:'Organization Statistics' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Organization overall</div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div> -->\n");
      out.write("\t\t\n");
      out.write("\t\t <div title=\"Imports history\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'ImportedHistory.action?organizationId='+$('#filterorg').val(), kTitle:'Imports history' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Imports history</div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write(" \t<div title=\"Transformations history\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'TransformedHistory.action?organizationId='+$('#filterorg').val(), kTitle:'Transformations history' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Transformations history</div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<div title=\"Publications history\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'PublishedHistory.action?organizationId='+$('#filterorg').val(), kTitle:'Publications history' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Publications history </div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t<!-- \t<div title=\"OAI Status\"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'OaiStatus.action?organizationId='+$('#filterorg').val(), kTitle:'OAI Status' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">OAI Status </div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div> -->\t\t\n");
      out.write("\t\n");
      out.write("\t\t\n");
      out.write("\t<div title=\"Project overall statistics \"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'ProjectStatistics.action', kTitle:'Project overall statistics' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Project overall statistics </div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t\t</div>\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div title=\"Project publication statistics \"\n");
      out.write("\t\t\tonclick=\"var cp=$($(this).closest('div[id^=kp]'));$(cp).find('div.k-active').removeClass('k-active');$(this).toggleClass('k-active');$K.kaiten('removeChildren',cp, false);$K.kaiten('load',{kConnector:'html.page', url:'ProjectPublications.action', kTitle:'Project publications statistics' });\"\n");
      out.write("\t\t\tclass=\"items navigable\" style=\"min-height:30px;height:auto;\">\n");
      out.write("\t\t\t<div class=\"label\">Project publications statistics </div>\n");
      out.write("\t\t\t<div class=\"tail\"></div>\n");
      out.write("\t</div>\t\n");
      out.write("  \n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write(" \t\n");
      out.write(" ");
      out.write("\n");
      out.write("\t\n");
      out.write(" \n");
      out.write(" \n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f0 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.SetTag.class);
    _jspx_th_s_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/datastatistics.jsp(5,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fset_005f0.setVar("orgId");
    // /WEB-INF/jsp/datastatistics.jsp(5,3) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fset_005f0.setValue("filterOrg");
    int _jspx_eval_s_005fset_005f0 = _jspx_th_s_005fset_005f0.doStartTag();
    if (_jspx_th_s_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/datastatistics.jsp(6,4) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fif_005f0.setTest("orgid==-1");
    int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
    if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_s_005fif_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_s_005fif_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("    ");
        if (_jspx_meth_s_005fset_005f1(_jspx_th_s_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_s_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:set
    org.apache.struts2.views.jsp.SetTag _jspx_th_s_005fset_005f1 = (org.apache.struts2.views.jsp.SetTag) _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.SetTag.class);
    _jspx_th_s_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_s_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_s_005fif_005f0);
    // /WEB-INF/jsp/datastatistics.jsp(7,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fset_005f1.setVar("orgId");
    // /WEB-INF/jsp/datastatistics.jsp(7,4) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fset_005f1.setValue("user.dbID");
    int _jspx_eval_s_005fset_005f1 = _jspx_th_s_005fset_005f1.doStartTag();
    if (_jspx_th_s_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_s_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_s_005fselect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:select
    org.apache.struts2.views.jsp.ui.SelectTag _jspx_th_s_005fselect_005f0 = (org.apache.struts2.views.jsp.ui.SelectTag) _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody.get(org.apache.struts2.views.jsp.ui.SelectTag.class);
    _jspx_th_s_005fselect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fselect_005f0.setParent(null);
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = theme type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setTheme("simple");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = cssStyle type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setCssStyle("width:200px");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = name type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setName("filterorg");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setId("filterorg");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = list type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setList("allOrgs");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = listKey type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setListKey("dbID");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = listValue type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setListValue("name");
    // /WEB-INF/jsp/datastatistics.jsp(27,3) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fselect_005f0.setValue("orgId");
    int _jspx_eval_s_005fselect_005f0 = _jspx_th_s_005fselect_005f0.doStartTag();
    if (_jspx_th_s_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fselect_0026_005fvalue_005ftheme_005fname_005flistValue_005flistKey_005flist_005fid_005fcssStyle_005fnobody.reuse(_jspx_th_s_005fselect_005f0);
    return false;
  }
}
