/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-04-04 13:07:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.log4j.Logger;
import gr.ntua.ivml.mint.persistent.User;
import gr.ntua.ivml.mint.db.DB;
import gr.ntua.ivml.mint.util.Config;
import java.util.List;
import gr.ntua.ivml.mint.persistent.Organization;
import gr.ntua.ivml.mint.persistent.DataUpload;
import gr.ntua.ivml.mint.db.DB;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

 public final Logger log = Logger.getLogger(this.getClass());
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/top.jsp", Long.valueOf(1396604381000L));
    _jspx_dependants.put("/WEB-INF/jsp/_include.jsp", Long.valueOf(1395664770000L));
    _jspx_dependants.put("/WEB-INF/jsp/customize.tld", Long.valueOf(1395664770000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

log.debug( "Output rendered" );

User user=(User) request.getSession().getAttribute("user");
if( user != null ) {
	user = DB.getUserDAO().findById(user.getDbID(), false );
}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"images/browser_icon.ico\" rel=\"shortcut icon\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- new stuff here -->\r\n");
      out.write("<script src=\"js/fileuploader.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery/jquery.layout.default.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/kaiten.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery/Aristo/Aristo.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery/jquery.toolbar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/fileuploader.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/widgets/schemaTree.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/widgets/valueBrowser.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/widgets/thesaurusBrowser.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/xsdmapping/mappingElement.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/xsdmapping/annotatorElement.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/xsdmapping/xsdmapping.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/annotator/annotator.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/slickgrid/slick.grid.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/chosen/chosen.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"js/slickgrid/examples/examples.css\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/pagination.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/athform.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/evol.colorpicker.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"css/core.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/mint2.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- highlighter  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/highlighter/styles/shThemeMint.css\"/>  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/highlighter/styles/shCore.css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/highlighter/scripts/XRegExp.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/highlighter/scripts/shCore.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/highlighter/scripts/shBrushXml.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <script type=\"text/javascript\" src=\"js/highlighter/scripts/shBrushPlain.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!-- highlighter end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/slickgrid/lib/jquery-1.7.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/mint2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.tools.min.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery-ui.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.layout.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.jeditable.mini.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.qtip.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.pagination.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.blockUI.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jquery.toolbar.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/jstree/jquery.jstree.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jkaiten.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/chosen/chosen.jquery.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ace/ace.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ace/mode-xml.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/ace/mode-groovy.js\"> </script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/lib/jquery.event.drag-2.0.min.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/slick.core.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/slick.grid.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/slick.formatters.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/slick.editors.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/slick.dataview.js\"> </script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/plugins/slick.checkboxselectcolumn.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slickgrid/plugins/slick.rowselectionmodel.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/documentation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/documentation-resources.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/preferences.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/widgets/schemaTree.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/widgets/valueBrowser.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/widgets/thesaurusBrowser.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/widgets/itemBrowser.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/widgets/itemPreview.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingAjax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingArea.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingElement.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/annotator/annotatorElement.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/annotator/annotatorFunction.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingFunction.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingValues.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingCondition.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/mappingView.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/xsdmappingeditor.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/xsdmappingPreview.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/xsdmappingValidation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/xsdmappingNavigation.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/xsdmapping/xsdmappingPreferences.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mint2/annotator/annotator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/modalPopup.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--  used stuff  (replace all YUI)-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/evol.colorpicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/labelRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/itemRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/mappingRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/outputxsdRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/importRequest.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/adminRequest.js\"></script>\r\n");
      out.write("<script src=\"js/oaiRequest.js\" type=\"text/javascript\"></script>\r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \tgoogle.load('visualization', '1', {'packages':['table']});\r\n");
      out.write("    google.load('visualization', '1', {'packages':['corechart']});\r\n");
      out.write("    google.load('visualization', '1.0', {'packages':['controls']});\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("<title>");
      out.print(Config.get("mint.title"));
      out.write("</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"home_logo\" style=\"display: none\">\n");
      out.write("\t");
      if (_jspx_meth_cst_005fcustomJsp_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"home_custom\" style=\"display: none\">\n");
      out.write("\t");
      if (_jspx_meth_cst_005fcustomJsp_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
 String sessionId = request.getSession().getId();


      out.write("\n");
      out.write("<script>\n");
      out.write("\tdocument.title = \"MINT Home\";\n");
      out.write("\tmintTitle = \"");
      out.print( Config.get("mint.title") );
      out.write("\";\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("\t#k-topbar #logout-button {\n");
      out.write("\t    border : 0 none;\n");
      out.write("        background:url('images/logout.png') no-repeat;\n");
      out.write("        background-position: 6px 7px;\n");
      out.write("        width:32px;\n");
      out.write("        height:32px;\n");
      out.write("\t}\t\n");
      out.write("\n");
      out.write("\t#k-topbar #logout-button:hover {\n");
      out.write("\t    border : 0 none;\n");
      out.write("        background:url('images/logout_hover.png') no-repeat;\n");
      out.write("        background-position: 6px 7px;\n");
      out.write("        width:32px;\n");
      out.write("        height:32px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t#k-topbar #help-button {\n");
      out.write("\t    border : 0 none;\n");
      out.write("        background:url('images/help.png') no-repeat;\n");
      out.write("        background-position: 4px 4px;\n");
      out.write("        width:32px;\n");
      out.write("        height:32px;\n");
      out.write("\t}\t\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tfunction recentMappings() {\n");
      out.write("\t\tvar recent = $(\"<div>\");\n");
      out.write("\t\t\n");
      out.write("\t\t$.get(\"Recent\", {\n");
      out.write("\t\t\ttype: \"mapping\"\n");
      out.write("\t\t}, function(result) {\t\t\t\n");
      out.write("\t\t\tif(result.mappings != undefined) {\n");
      out.write("\t\t\t\trecent.append($(\"<div>\").addClass(\"summary\").append($(\"<div>\").addClass(\"label\").text(\"Recent mappings\")));\n");
      out.write("\t\t\t\tfor(var i in result.mappings) {\n");
      out.write("\t\t\t\t\tvar entry = result.mappings[i];\n");
      out.write("\t\t\t\t\tvar div = kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : \"Mapping: \" + entry.mapping.name,\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"MappingOptions.action?uploadId=\" + entry.dataset.dbID + \"&selaction=editmaps&selectedMapping=\" + entry.mapping.dbID, kTitle:\"Mapping\" }\n");
      out.write("\t\t\t\t\t}).css({ height: \"50px\" }).appendTo(recent);\n");
      out.write("\t\t\t\t\tdiv.append($(\"<div>\").addClass(\"label\").css({ top: \"20px\" }).text(\"Dataset: \" + entry.dataset.name));\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}, \"json\");\n");
      out.write("\t\t\n");
      out.write("\t\treturn recent;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction recentAnnotations() {\n");
      out.write("\t\tvar recent = $(\"<div>\");\n");
      out.write("\t\t\n");
      out.write("\t\t$.get(\"Recent\", {\n");
      out.write("\t\t\ttype: \"annotation\"\n");
      out.write("\t\t}, function(result) {\n");
      out.write("\t\t\trecent.append($(\"<div>\").addClass(\"summary\").append($(\"<div>\").addClass(\"label\").text(\"Recent annotations\")));\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(result.annotations != undefined) {\n");
      out.write("\t\t\t\tfor(var i in result.annotations) {\n");
      out.write("\t\t\t\t\tvar entry = result.annotations[i];\n");
      out.write("\t\t\t\t\tvar div = kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : \"Dataset: \" + entry.dataset.name,\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"Annotator.action?uploadId=\" + entry.dataset.dbID, kTitle:\"Annotation\" }\n");
      out.write("\t\t\t\t\t}).appendTo(recent);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}, \"json\");\n");
      out.write("\t\t\n");
      out.write("\t\treturn recent;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t(function($){\n");
      out.write("\t\t// keep a reference to Kaiten's container\n");
      out.write("\t\t$K = $('#container');\n");
      out.write("\t\t// initialize Kaiten\n");
      out.write("\t\t$K.kaiten({ \n");
      out.write("\t\t\t// 3 panels max. on the screen\n");
      out.write("\t\t\tcolumnWidth : '33%',\n");
      out.write("\t\t\toptionsSelector : '#custom-options-text',\n");
      out.write("\t\t\tstartup : function(dataFromURL){\n");
      out.write("\t\t\t\t// handle URL parameters sent when opening a panel in a new tab\n");
      out.write("\t\t\t\tif (dataFromURL)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\tthis.kaiten('load', dataFromURL);\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t// create the home panel HTML...\n");
      out.write("\t\t\t\t\tvar $navBlock = kTemplater.jQuery('block.navigation');\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tvar logo = $(\"<div>\").html($(\"#home_logo\").html());\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$navBlock.append(logo);\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.summary', {\n");
      out.write("\t\t\t\t\t\tlabel\t: 'MINT Home',\n");
      out.write("\t\t\t\t\t\tinfo\t: 'MINT services compose a web based platform designed and developed to facilitate aggregation initiatives for cultural heritage content and metadata in Europe.<a class=\"wiki-page\" href=\"http://mint.image.ece.ntua.gr/redmine/projects/mint/wiki/Introduction\">..(read more)</a>',\n");
      out.write("\t\t\t\t\t\ticonURL : 'images/mintsmall.png'\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("\n");
      out.write("\t\t\t\t\t");
if(user.hasRight(User.VIEW_DATA) ||user.hasRight(User.MODIFY_DATA) || user.hasRight(User.ADMIN) || user.hasRight(User.PUBLISH)){
					  long orgid=-1;
					  if(user.getOrganization()!=null){
						  orgid=user.getOrganization().getDbID();
					  }
					  
      out.write(" \n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\t// ...add navigation to a page on our server...\n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : 'My workspace',\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"ImportSummary.action?orgId=");
      out.print(orgid);
      out.write("\", kTitle:\"My workspace\" }\n");
      out.write("\t\t\t\t\t}));");
}
      out.write("\n");
      out.write("\t\t\t\t\t// ...add navigation to a page on our server...\n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : 'My account',\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"Profile.action\", kTitle:\"My account\" }\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t");
if(user.hasRight(User.ADMIN)){
      out.write(" \n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : 'Administration',\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"Management_input\", kTitle:\"Administration area\" }\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t");
if(user.hasRight(User.MODIFY_DATA) || user.hasRight(User.ADMIN)){
      out.write(" \t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : 'Locks',\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"LockSummary\", kTitle:\"Locks\" }\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("                ");
}
      out.write("                \n");
      out.write("                \n");
      out.write("                ");
if(user.hasRight(User.SUPER_USER) || Config.getBoolean("mint.enableGoalReports", false)){
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\tlabel : 'Data reports',\n");
      out.write("\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"DataReport\", kTitle:\"Data Report\" }\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("\t\t\t\t\t");
}
      out.write("                    \n");
      out.write("\t            \n");
      out.write("\t                ");
if(user.hasRight(User.SUPER_USER) || Config.getBoolean("mint.enableGoalReports")){
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t$navBlock.append(kTemplater.jQuery('line.navigation', {\n");
      out.write("\t\t\t\t\t\t\tlabel : 'Data statistics',\n");
      out.write("\t\t\t\t\t\t\tdata : { kConnector:\"html.page\", url:\"DataStatistics\", kTitle:\"Data Statistics\" }\n");
      out.write("\t\t\t\t\t\t}));\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("                    \n");
      out.write("\t           \n");
      out.write("\t           \n");
      out.write("\t\t\t\tthis.kaiten('load', function(data, $panel, $kaiten){\n");
      out.write("\t\t\t\t\t$panel.kpanel('setTitle', 'MINT Home');\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\treturn kTemplater.jQuery('panel.body', { content : $navBlock });\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\n");
      out.write("\t\t\t\t$($K.data(\"kaiten\").selectors.optionsCustom).hide();\n");
      out.write("\t\t\t\t$($K.data(\"kaiten\").selectors.appMenuContainer).append($(\"<button>\").attr(\"title\", \"Help\").attr(\"id\", \"help-button\").click(function () {\n");
      out.write("\t\t\t\t\tMint2.documentation.openDocumentation({\n");
      out.write("\t\t\t\t\t\tresource: \"/documentation\",\n");
      out.write("\t\t\t\t\t\ttarget: \"_blank\"\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}));\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t$($K.data(\"kaiten\").selectors.appMenuContainer).append($(\"<button>\").attr(\"title\", \"Logout\").attr(\"id\", \"logout-button\").click(function () {\n");
      out.write("\t\t\t\t\t\tlocation.href=\"Logout.action\";\n");
      out.write("\t\t\t\t\t}));\n");
      out.write("\t\t\t\t}\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t})(jQuery);\n");
      out.write("\t  \n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function () {\n");
      out.write("\t\tvar nav = $(\".block-nav\");\n");
      out.write("\t\tnav.append(recentMappings());\n");
      out.write("\t\tnav.append(recentAnnotations());\t\t\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_cst_005fcustomJsp_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cst:customJsp
    gr.ntua.ivml.mint.tagsupport.CustomJspTag _jspx_th_cst_005fcustomJsp_005f0 = (gr.ntua.ivml.mint.tagsupport.CustomJspTag) _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.get(gr.ntua.ivml.mint.tagsupport.CustomJspTag.class);
    _jspx_th_cst_005fcustomJsp_005f0.setPageContext(_jspx_page_context);
    _jspx_th_cst_005fcustomJsp_005f0.setParent(null);
    // /WEB-INF/jsp/home.jsp(8,1) name = jsp type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cst_005fcustomJsp_005f0.setJsp("home_logo.jsp");
    int _jspx_eval_cst_005fcustomJsp_005f0 = _jspx_th_cst_005fcustomJsp_005f0.doStartTag();
    if (_jspx_th_cst_005fcustomJsp_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.reuse(_jspx_th_cst_005fcustomJsp_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.reuse(_jspx_th_cst_005fcustomJsp_005f0);
    return false;
  }

  private boolean _jspx_meth_cst_005fcustomJsp_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  cst:customJsp
    gr.ntua.ivml.mint.tagsupport.CustomJspTag _jspx_th_cst_005fcustomJsp_005f1 = (gr.ntua.ivml.mint.tagsupport.CustomJspTag) _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.get(gr.ntua.ivml.mint.tagsupport.CustomJspTag.class);
    _jspx_th_cst_005fcustomJsp_005f1.setPageContext(_jspx_page_context);
    _jspx_th_cst_005fcustomJsp_005f1.setParent(null);
    // /WEB-INF/jsp/home.jsp(12,1) name = jsp type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_cst_005fcustomJsp_005f1.setJsp("home_custom.jsp");
    int _jspx_eval_cst_005fcustomJsp_005f1 = _jspx_th_cst_005fcustomJsp_005f1.doStartTag();
    if (_jspx_th_cst_005fcustomJsp_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.reuse(_jspx_th_cst_005fcustomJsp_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcst_005fcustomJsp_0026_005fjsp_005fnobody.reuse(_jspx_th_cst_005fcustomJsp_005f1);
    return false;
  }
}
