/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-03-24 15:39:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class organizationstatistics3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    \n");
      out.write("\n");
      out.write("      \n");
      out.write("     $(function(){\n");
      out.write("    \t var self = this;\n");
      out.write("    \t var content = $('#chart_div');\n");
      out.write("    \t var panel = content.closest('div[id^=\"kp\"]');\n");
      out.write("    \t $K.kaiten('maximize', panel);\n");
      out.write(" \n");
      out.write("\t\t\tdrawBarChart()\n");
      out.write("\t\t\n");
      out.write("\t  \n");
      out.write("\n");
      out.write(" \tfunction drawBarChart()\n");
      out.write("    {\n");
      out.write("\n");
      out.write("     $('#chart_div').html('<span><img src=\"images/buttons/loading.gif\" alt=\"\"></span>');\n");
      out.write("     $('#chart_1').html('<span><img src=\"images/buttons/loading.gif\" alt=\"\"></span>');\n");
      out.write("\n");
      out.write("     \n");
      out.write("     \n");
      out.write("    $.ajax({\n");
      out.write("    type:'GET',\n");
      out.write("    url:\"OrganizationStat.action\",\n");
      out.write("  \tdata:\"organizationId=\"+");
      out.print(request.getAttribute("getOrganizationId()"));
      out.write(",\n");
      out.write("    success:function(data) {\n");
      out.write("\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t/*   var cdata = google.visualization.arrayToDataTable([\n");
      out.write("\t\t\t ['Organization', 'Imported', 'Transformed', 'Published', 'Published to EUscreenXL-EDM','Published to ItemClip v2','Published to Series v2','Aggregation Goal','Core Goal'],\n");
      out.write("\t\t\t [data.result.Name, data.result.Imported , data.result.Transformed , data.result.Published , data.result.PublishedtoEDM ,data.result.PublishedtoItemClipv2,data.result.PublishedtoSeriesv2,data.result.AggregationTarget,data.result.CoreTarget]\n");
      out.write("\t\t\t                                                    \n");
      out.write("\t\t\t ]);\n");
      out.write("\t\t\t */\n");
      out.write("\n");
      out.write("\t\t\t result = data.result\n");
      out.write("\t\t\t keys = Object.keys(result);\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t/*  var cdata = {};\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t var cols = []];\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t var rows = []; */\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t var cdata = new google.visualization.DataTable();\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t for (var key in keys){\n");
      out.write("\t\t\t\t cdata.addColumn('string',keys[key]);\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\t var rows = [];\n");
      out.write("\t\t\t var c = {};\n");
      out.write("\t\t\t var values = [];\n");
      out.write("\t\t\t for (var key in keys){\n");
      out.write("\t\t\t\t value = result[keys[key]];\n");
      out.write("\t\t\t\t obj ={};\n");
      out.write("\t\t\t\tobj.push({v,value});\n");
      out.write("\t\t\t\t console.log(value);\n");
      out.write("\t\t\t\t values.push(obj);\n");
      out.write("\t\t\t }\n");
      out.write("\t\t\tc[c] = values;\n");
      out.write("\t\t\trows.push(c);\t \n");
      out.write("\t\t\t \n");
      out.write("\t\t\t console.log(rows);\n");
      out.write("\t\t\t\tcdata.addRows(rows); \n");
      out.write("\t\t\t /* cdata.addRow(row); */\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("    \t\t  var options = {'title':'Items counted : ");
      out.print(request.getAttribute("getName()"));
      out.write("'}\n");
      out.write("\n");
      out.write("    \t\t  var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));\n");
      out.write("\t\t\t  chart.draw(cdata, options);\n");
      out.write("\t\t\t  var chart = new google.visualization.Table(document.getElementById('chart_1'));\n");
      out.write("\t\t\t  chart.draw(cdata, options);\n");
      out.write(" \t\t\t } \n");
      out.write("    \t\t\t\t\t\t\t\t\n");
      out.write("       \n");
      out.write("    \n");
      out.write("    });\n");
      out.write("    }\n");
      out.write("     })\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<div class=\"panel-body\"  style=\"height: 100%; width: 100%\">\n");
      out.write("\t<div class=\"block-nav\"  style=\"height: 100%; width: 100%\">\n");
      out.write("\t\t<div class=\"summary\">\n");
      out.write("\t\t\t<div class=\"label\">\n");
      out.write("\t\t\t");
      out.print(request.getAttribute("getName()"));
      out.write("</div>\n");
      out.write("\t\t\t<div class=\"info\"><br/></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Overall</h3>\n");
      out.write("\t\t<div id=\"chart_div\"  style=\"height: 50%; width: 100%\"></div>\n");
      out.write("\t\t\t<div id=\"chart_1\"  style=\"height: 50%; width: 100%\"></div>\n");
      out.write("       \t\t\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
