/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2014-03-26 15:32:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class publishedhistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<head>\n");
      out.write("<!--Load the AJAX API-->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("     $(function(){\n");
      out.write("    \t var self = this;\n");
      out.write("    \t var content = $('#chart');\n");
      out.write("    \t var panel = content.closest('div[id^=\"kp\"]');\n");
      out.write("    \t $K.kaiten('maximize', panel);\n");
      out.write("    \t drawChart()\n");
      out.write("         function drawChart()\n");
      out.write("         {\n");
      out.write("         $('#chart').html('<span><img src=\"images/buttons/loading.gif\" alt=\"\"></span>');\n");
      out.write("         $.ajax({\n");
      out.write("         type:'GET',\n");
      out.write("         url:\"UrlApi?isApi=true&action=list&type=Publication\",data:\"organizationId=\"+");
      out.print(request.getAttribute("getOrganizationId()"));
      out.write(",\n");
      out.write("         success:function(data) {\n");
      out.write("         var sets = [];\n");
      out.write("         var headers = [\"Parent Dataset Name\",\"Publication Date\",\"Published Items\",\"Invalid Items\",\"Target Schema\",\"Mapping\"];\n");
      out.write("         sets.push(headers);\n");
      out.write("         for(var i=0; i<data.result.length; i++)\n");
      out.write("         {\n");
      out.write("        \t \tvar parent = data.result[i].parentDataset;\n");
      out.write("        \t    var date = new Date(data.result[i].publicationEndDate);\n");
      out.write("        \t    var items = data.result[i].publishedItems;\n");
      out.write("        \t    var invalid =  data.result[i].invalidItems;\n");
      out.write("        \t    var target = data.result[i].targetSchema;\n");
      out.write("        \t    var mapping = data.result[i].mappingUsed;\n");
      out.write("        \t    sets.push([parent, date,items,invalid,target,mapping]);\n");
      out.write("   \n");
      out.write("         }   \n");
      out.write("        var data = google.visualization.arrayToDataTable(sets);\n");
      out.write("     \tvar options = {'title': '");
      out.print(request.getAttribute("getName()"));
      out.write("'};\n");
      out.write("         \n");
      out.write("        var table = new google.visualization.Table(document.getElementById('chart'));\n");
      out.write("        table.draw(data, options);\n");
      out.write("        \n");
      out.write("        var grouped_dt = google.visualization.data.group(\n");
      out.write("        \t      data, [4],[{'column': 2, 'aggregation': google.visualization.data.sum, 'type': 'number'}]);\n");
      out.write("        \n");
      out.write("        var grouped_table = new google.visualization.ColumnChart(document.getElementById('grouped_table'));\n");
      out.write("        grouped_table.draw(grouped_dt, options);\n");
      out.write("        \n");
      out.write("        }\n");
      out.write("        });   \n");
      out.write("        }     \n");
      out.write("     })\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"panel-body\" style=\"height: 100%; width: 100%\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t  <pre class='brush: plain'></pre>\n");
      out.write(" \t<div class=\"block-nav\"  style=\"height: 100%; width: 100%\" >\n");
      out.write("\t\t<div class=\"summary\">\n");
      out.write("\t\t\t<div class=\"label\">\n");
      out.write("\t\t\t");
      out.print(request.getAttribute("getName()"));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"info\"><br/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<h3>Publications</h3>\t\n");
      out.write("\t\t<div id=\"chart\" style=\"height: 50%; width: 100%\"></div>\n");
      out.write("\t\t\n");
      out.write("\t\t<h3>Published items per schema</h3>\t\n");
      out.write("       <div id=\"grouped_table\" style=\"height: 50%; width: 60%\"></div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
