package gr.ntua.ivml.mint.db;

import gr.ntua.ivml.mint.util.Tuple;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.openjena.atlas.logging.Log;

/**
 * Class to use a key value store table.
 * 
 * @author Arne Stabenau 
 *
 */
public class Meta {
	
	/**
	 * Generate a key based on objects class and, if it is a database object, dbID
	 * @param object
	 * @return the key (example: gr.ntua.ivml.mint.persistent.User[1000])
	 */
	public static String generateKey(Object object) {
		Long id = new Long(0);
		Class<?> objectClass = object.getClass();
		try {
			Method dbID = objectClass.getMethod("getDbID");
			if(dbID != null) id = (Long) dbID.invoke(object);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return object.getClass().getName() + "[" + id.longValue() + "]"; 
	}
	
	/**
	 * Generate a key based on the objects class, the object's dbID if it exists, and a property name
	 * @param object
	 * @param property
	 * @return the key (example gr.ntua.ivml.mint.persistent.User[1000].property)
	 */
	public static String generateKey(Object object, String property) {
		return Meta.generateKey(object) + "." + property;
	}


	/**
	 * Puts key and value String in db. If key exists, the value is replaced. 
	 * @param key
	 * @param value
	 */
	public static void put( String key, String value ) {
		String result = Meta.get(key);
		System.out.println("Meta: original value: " + key + " = " + result);
		
		if(result == null) {
			DB.getStatelessSession().createSQLQuery("insert into meta( meta_id, meta_key, meta_value ) " +
					" values( nextval('seq_meta_id'), ?, ? )")
					.setParameter( 0, key )
					.setParameter( 1, value )
					.executeUpdate();
		} else {
			DB.getStatelessSession().createSQLQuery("update meta set meta_value = ? where meta_key = ?")
					.setParameter( 0, value)
					.setParameter( 1, key)
					.executeUpdate();
		}

		DB.getStatelessSession().getTransaction().commit();
		DB.getStatelessSession().beginTransaction();
	}
	
	/**
	 * Puts assigns a value to a key generated by the specified object and property
	 * @param object
	 * @param property
	 * @param value
	 */
	public static void put(Object object, String property, String value ) {
		String key = Meta.generateKey(object, property);
		Meta.put(key, value);
	}
	
	/**
	 * Return null on not found. Gets the first entry with this key.
	 * Multiple same key entries are allowed, but not recommended.
	 * 
	 * You can get the with getLike() out again.
	 * @param key
	 * @return
	 */
	public static String get( String key ) {
		String res = (String ) DB.getStatelessSession().createSQLQuery( "select meta_value from meta where meta_key = ? order by meta_id")
		.setParameter(0,key)
		.uniqueResult();
		return res;
	}
	
	/**
	 * Gets a value stored for this object's property.
	 * @param object
	 * @param property
	 * @return the value
	 */
	public static String get(Object object, String property) {
		String key = Meta.generateKey(object, property);
		return Meta.get(key);
	}
	
	/**
	 * Delete all entries with exactly the given key.
	 * @param key
	 */
	public static void delete( String key ) {
		DB.getStatelessSession().createSQLQuery("delete from meta " +
		" where meta_key = ?")
		.setParameter( 0, key )
		.executeUpdate();	
		DB.getStatelessSession().getTransaction().commit();
		DB.getStatelessSession().beginTransaction();

	}
	
	/**
	 * Deletes entries for the specified object and property.
	 * @param object
	 * @param property
	 */
	public static void delete(Object object, String property) {
		String key = Meta.generateKey(object, property);
		Meta.delete(key);
	}
	
	/**
	 * Get a list of key values that fit the 'LIKE' pattern
	 * @param pattern
	 * @return
	 */
	public static List<Tuple<String, String>> getLike( String pattern ) {
		// broken on oreo ..
		List<Object[]> queryRes = (List<Object[]>) DB.getStatelessSession().createSQLQuery( "select meta_key, meta_value from meta where meta_key like ? order by meta_id")
		.setParameter( 0, pattern )
		.list();
		if(( queryRes == null) || ( queryRes.isEmpty())) return Collections.emptyList();

		List<Tuple<String, String>> res = new ArrayList<Tuple<String, String>>();
		for( Object[] s2: queryRes ) {
			res.add( new Tuple<String, String>( s2[0].toString(), s2[1].toString()));
		}
		return res;
	}

	
	/**
	 * Gets all entries for the specified object.
	 * @param object
	 * @return
	 */
	public static List<Tuple<String, String>> getAllProperties(Object object) {
		String key = Meta.generateKey(object) + ".%";
		return Meta.getLike(key);
	}
	
	/**
	 * Delete entries where the key fits the 'LIKE' pattern.
	 * @param pattern
	 */
	public static void deleteLike( String pattern ) {
		DB.getStatelessSession().createSQLQuery("delete from meta " +
		" where meta_key like ?")
		.setParameter( 0, pattern )
		.executeUpdate();		
		DB.getStatelessSession().getTransaction().commit();
		DB.getStatelessSession().beginTransaction();
	}
	
	/**
	 * Deletes all entries for the specified object.
	 * @param object
	 */
	public static void deleteAllProperties( Object object ) {
		String key = Meta.generateKey(object) + ".%";
		Meta.deleteLike(key);
	}
	
	/**
	 * helps with testing
	 */
	
	public static int countLike( String pattern ) {
		BigInteger res = (BigInteger ) DB.getStatelessSession().createSQLQuery( "select count(*) from meta where meta_key like ?")
		.setParameter(0,pattern)
		.uniqueResult();
		
		return res.intValue();
	}
}
